const { Zenith } = require('../../lib/functions');
const config = require('../../config');

const countries = {
  'AF': '🇦🇫 Afghanistan',
  'AL': '🇦🇱 Albania',
  'DZ': '🇩🇿 Algeria',
  'AD': '🇦🇩 Andorra',
  'AO': '🇦🇴 Angola',
  'AR': '🇦🇷 Argentina',
  'AM': '🇦🇲 Armenia',
  'AU': '🇦🇺 Australia',
  'AT': '🇦🇹 Austria',
  'AZ': '🇦🇿 Azerbaijan',
  'BH': '🇧🇭 Bahrain',
  'BD': '🇧🇩 Bangladesh',
  'BY': '🇧🇾 Belarus',
  'BE': '🇧🇪 Belgium',
  'BJ': '🇧🇯 Benin',
  'BT': '🇧🇹 Bhutan',
  'BO': '🇧🇴 Bolivia',
  'BA': '🇧🇦 Bosnia and Herzegovina',
  'BW': '🇧🇼 Botswana',
  'BR': '🇧🇷 Brazil',
  'BN': '🇧🇳 Brunei',
  'BG': '🇧🇬 Bulgaria',
  'BF': '🇧🇫 Burkina Faso',
  'BI': '🇧🇮 Burundi',
  'KH': '🇰🇭 Cambodia',
  'CM': '🇨🇲 Cameroon',
  'CA': '🇨🇦 Canada',
  'CV': '🇨🇻 Cape Verde',
  'CF': '🇨🇫 Central African Republic',
  'TD': '🇹🇩 Chad',
  'CL': '🇨🇱 Chile',
  'CN': '🇨🇳 China',
  'CO': '🇨🇴 Colombia',
  'KM': '🇰🇲 Comoros',
  'CR': '🇨🇷 Costa Rica',
  'HR': '🇭🇷 Croatia',
  'CU': '🇨🇺 Cuba',
  'CY': '🇨🇾 Cyprus',
  'CZ': '🇨🇿 Czech Republic',
  'DK': '🇩🇰 Denmark',
  'DJ': '🇩🇯 Djibouti',
  'DO': '🇩🇴 Dominican Republic',
  'TL': '🇹🇱 East Timor',
  'EC': '🇪🇨 Ecuador',
  'EG': '🇪🇬 Egypt',
  'SV': '🇸🇻 El Salvador',
  'GQ': '🇬🇶 Equatorial Guinea',
  'ER': '🇪🇷 Eritrea',
  'EE': '🇪🇪 Estonia',
  'ET': '🇪🇹 Ethiopia',
  'FJ': '🇫🇯 Fiji',
  'FI': '🇫🇮 Finland',
  'FR': '🇫🇷 France',
  'GA': '🇬🇦 Gabon',
  'GM': '🇬🇲 Gambia',
  'GE': '🇬🇪 Georgia',
  'DE': '🇩🇪 Germany',
  'GH': '🇬🇭 Ghana',
  'GR': '🇬🇷 Greece',
  'GT': '🇬🇹 Guatemala',
  'GN': '🇬🇳 Guinea',
  'GW': '🇬🇼 Guinea-Bissau',
  'GY': '🇬🇾 Guyana',
  'HT': '🇭🇹 Haiti',
  'HN': '🇭🇳 Honduras',
  'HU': '🇭🇺 Hungary',
  'IS': '🇮🇸 Iceland',
  'IN': '🇮🇳 India',
  'ID': '🇮🇩 Indonesia',
  'IR': '🇮🇷 Iran',
  'IQ': '🇮🇶 Iraq',
  'IE': '🇮🇪 Ireland',
  'IL': '🇮🇱 Israel',
  'IT': '🇮🇹 Italy',
  'CI': '🇨🇮 Ivory Coast',
  'JM': '🇯🇲 Jamaica',
  'JP': '🇯🇵 Japan',
  'JO': '🇯🇴 Jordan',
  'KZ': '🇰🇿 Kazakhstan',
  'KE': '🇰🇪 Kenya',
  'KI': '🇰🇮 Kiribati',
  'KR': '🇰🇷 South Korea',
  'KW': '🇰🇼 Kuwait',
  'KG': '🇰🇬 Kyrgyzstan',
  'LA': '🇱🇦 Laos',
  'LV': '🇱🇻 Latvia',
  'LB': '🇱🇧 Lebanon',
  'LS': '🇱🇸 Lesotho',
  'LR': '🇱🇷 Liberia',
  'LY': '🇱🇾 Libya',
  'LI': '🇱🇮 Liechtenstein',
  'LT': '🇱🇹 Lithuania',
  'LU': '🇱🇺 Luxembourg',
  'MK': '🇲🇰 North Macedonia',
  'MG': '🇲🇬 Madagascar',
  'MW': '🇲🇼 Malawi',
  'MY': '🇲🇾 Malaysia',
  'MV': '🇲🇻 Maldives',
  'ML': '🇲🇱 Mali',
  'MT': '🇲🇹 Malta',
  'MH': '🇲🇭 Marshall Islands',
  'MR': '🇲🇷 Mauritania',
  'MU': '🇲🇺 Mauritius',
  'MX': '🇲🇽 Mexico',
  'FM': '🇫🇲 Micronesia',
  'MD': '🇲🇩 Moldova',
  'MC': '🇲🇨 Monaco',
  'MN': '🇲🇳 Mongolia',
  'ME': '🇲🇪 Montenegro',
  'MA': '🇲🇦 Morocco',
  'MZ': '🇲🇿 Mozambique',
  'MM': '🇲🇲 Myanmar',
  'NA': '🇳🇦 Namibia',
  'NR': '🇳🇷 Nauru',
  'NP': '🇳🇵 Nepal',
  'NL': '🇳🇱 Netherlands',
  'NZ': '🇳🇿 New Zealand',
  'NI': '🇳🇮 Nicaragua',
  'NE': '🇳🇪 Niger',
  'NG': '🇳🇬 Nigeria',
  'NO': '🇳🇴 Norway',
  'OM': '🇴🇲 Oman',
  'PK': '🇵🇰 Pakistan',
  'PW': '🇵🇼 Palau',
  'PS': '🇵🇸 Palestine',
  'PA': '🇵🇦 Panama',
  'PG': '🇵🇬 Papua New Guinea',
  'PY': '🇵🇾 Paraguay',
  'PE': '🇵🇪 Peru',
  'PH': '🇵🇭 Philippines',
  'PL': '🇵🇱 Poland',
  'PT': '🇵🇹 Portugal',
  'QA': '🇶🇦 Qatar',
  'RO': '🇷🇴 Romania',
  'RU': '🇷🇺 Russia',
  'RW': '🇷🇼 Rwanda',
  'KN': '🇰🇳 Saint Kitts and Nevis',
  'LC': '🇱🇨 Saint Lucia',
  'VC': '🇻🇨 Saint Vincent and the Grenadines',
  'WS': '🇼🇸 Samoa',
  'SM': '🇸🇲 San Marino',
  'ST': '🇸🇹 Sao Tome and Principe',
  'SA': '🇸🇦 Saudi Arabia',
  'SN': '🇸🇳 Senegal',
  'RS': '🇷🇸 Serbia',
  'SC': '🇸🇨 Seychelles',
  'SL': '🇸🇱 Sierra Leone',
  'SG': '🇸🇬 Singapore',
  'SK': '🇸🇰 Slovakia',
  'SI': '🇸🇮 Slovenia',
  'SB': '🇸🇧 Solomon Islands',
  'SO': '🇸🇴 Somalia',
  'ZA': '🇿🇦 South Africa',
  'SS': '🇸🇸 South Sudan',
  'ES': '🇪🇸 Spain',
  'LK': '🇱🇰 Sri Lanka',
  'SD': '🇸🇩 Sudan',
  'SR': '🇸🇷 Suriname',
  'SE': '🇸🇪 Sweden',
  'CH': '🇨🇭 Switzerland',
  'SY': '🇸🇾 Syria',
  'TW': '🇹🇼 Taiwan',
  'TJ': '🇹🇯 Tajikistan',
  'TZ': '🇹🇿 Tanzania',
  'TH': '🇹🇭 Thailand',
  'TG': '🇹🇬 Togo',
  'TO': '🇹🇴 Tonga',
  'TT': '🇹🇹 Trinidad and Tobago',
  'TN': '🇹🇳 Tunisia',
  'TR': '🇹🇷 Turkey',
  'TM': '🇹🇲 Turkmenistan',
  'TV': '🇹🇻 Tuvalu',
  'UG': '🇺🇬 Uganda',
  'UA': '🇺🇦 Ukraine',
  'AE': '🇦🇪 United Arab Emirates',
  'GB': '🇬🇧 United Kingdom',
  'US': '🇺🇸 United States',
  'UY': '🇺🇾 Uruguay',
  'UZ': '🇺🇿 Uzbekistan',
  'VU': '🇻🇺 Vanuatu',
  'VA': '🇻🇦 Vatican City',
  'VE': '🇻🇪 Venezuela',
  'VN': '🇻🇳 Vietnam',
  'YE': '🇾🇪 Yemen',
  'ZM': '🇿🇲 Zambia',
  'ZW': '🇿🇼 Zimbabwe',
};
                  

Zenith({ usage: 'flag', 
         desc: 'Guess country flag', 
         category: 'GAMES 3D', 
      }, async (vorterx, m, react, { args }) => {
           
  const countryCodes = Object.keys(countries);
  const randomCountryCode = countryCodes[Math.floor(Math.random() * countryCodes.length)];

  const correctFlagAndName = countries[randomCountryCode];
  const [correctFlag, correctCountryName] = correctFlagAndName.split(' ');

  vorterx.sendMessage(m.chat, {
    text: `Guess the country flag for ${correctCountryName}:\n${correctFlag}`,
    options: [
      { label: 'A', value: 'Option A' },
      { label: 'B', value: 'Option B' },
      { label: 'C', value: 'Option C' },
      { label: 'D', value: 'Option D' },
      { label: 'E', value: 'Option E' },
      { label: 'F', value: 'Option F' },
      { label: 'G', value: 'Option G' },
      { label: 'H', value: 'Option H' },
      { label: 'I', value: 'Option I' },
      { label: 'J', value: 'Option J' },
      { label: 'K', value: 'Option K' },
      { label: 'L', value: 'Option L' },
      { label: 'M', value: 'Option M' },
      { label: 'N', value: 'Option N' },
      { label: 'O', value: 'Option O' },
      { label: 'P', value: 'Option P' },
      { label: 'Q', value: 'Option Q' },
      { label: 'R', value: 'Option R' },
      { label: 'S', value: 'Option S' },
      { label: 'T', value: 'Option T' },
      { label: 'U', value: 'Option U' },
      { label: 'V', value: 'Option V' },
      { label: 'W', value: 'Option W' },
      { label: 'X', value: 'Option X' },
      { label: 'Y', value: 'Option Y' },
      { label: 'Z', value: 'Option Z' },
    ],
    onOptions: async (selectedOption) => {
          
      if (selectedOption === 'Option A') {
        vorterx.sendMessage(m.chat, {
          text: `Congratulations, ${m.pushName}! You guessed the correct flag for ${correctCountryName}.`,
        });
      } else {
        vorterx.sendMessage(m.chat, {
          text: `Sorry, ${m.pushName}. That's not the correct flag for ${correctCountryName}.`,
        });
      }
    },
  });
});
    
